
export const questions = [
    "A bird",
    "A drink",
    "A fish",
    "A girl\u2019s name",
    "A relative",
    "A river",
    "Acronyms",
    "An animal",
    "Animal noises",
    "Animals in books or movies",
    "Appliances",
    "Authors",
    "Awards/ceremonies",
    "Baby foods",
    "Bad habits",
    "Beers",
    "Birds",
    "Board games",
    "Bodies of water",
    "Breakfast foods",
    "Capitals",
    "Card games",
    "Cars",
    "Cartoon characters",
    "Celebrities",
    "Children\u2019s books",
    "Christmas songs",
    "Cities",
    "Clothing",
    "Colleges/Universities",
    "Colors",
    "Computer parts",
    "Computer programs",
    "Cooking utensils",
    "Cosmetics/Toiletries",
    "Countries",
    "Crimes",
    "Diet foods",
    "Diseases",
    "Drugs that are abused",
    "Electronic gadgets",
    "Ethnic foods",
    "Excuses for being late",
    "Famous duos and trios",
    "Fears",
    "Fictional characters",
    "Fish",
    "Flowers",
    "Food/Drink that is green",
    "Foods you eat raw",
    "Footwear",
    "Foreign cities",
    "Foreign words used in English",
    "Fruits",
    "Game terms",
    "Games",
    "Gifts",
    "Halloween costumes",
    "Heroes",
    "Historic events",
    "Historical Figures",
    "Hobbies",
    "Holiday Activities",
    "Holidays",
    "Honeymoon spots",
    "Household chores",
    "Ice cream flavors",
    "Insects",
    "Internet lingo",
    "Items in a catalog",
    "Items in a kitchen",
    "Items in a suitcase",
    "Items in a vending machine",
    "Items in this room",
    "Items you save up to buy",
    "Items you take on a road trip",
    "Kinds of candy",
    "Kinds of soup",
    "Leisure activities",
    "Magazines",
    "Math terms",
    "Menu items",
    "Movie titles",
    "Musical Instruments",
    "Musical groups",
    "Names used in songs",
    "Nicknames",
    "Notorious people",
    "Occupations",
    "Ocean things",
    "Offensive words",
    "Olympic events",
    "Parks",
    "Parts of the body",
    "Personality traits",
    "Pizza toppings",
    "Places in Europe",
    "Places to hangout",
    "Provinces or States",
    "Reasons to call 911",
    "Reasons to make a phone call",
    "Reasons to quit your job",
    "Reasons to take out a loan",
    "Reptiles/Amphibians",
    "Restaurants",
    "Sandwiches",
    "School subjects",
    "School supplies",
    "Seafood",
    "Software",
    "Something you keep hidden",
    "Something you\u2019re afraid oF",
    "Song titles",
    "Spices/Herbs",
    "Spicy foods",
    "Sports",
    "Sports Stars",
    "Sports equipment",
    "Sports played outdoors",
    "States",
    "Stones/Gems",
    "Store names",
    "TV Shows",
    "TV Stars",
    "Television stars",
    "Terms of endearment",
    "Things at a carnival",
    "Things at a circus",
    "Things at a football game",
    "Things found at a bar",
    "Things found in New York",
    "Things found in a desk",
    "Things found in a hospital",
    "Things in a grocery store",
    "Things in a medicine cabinet",
    "Things in a park",
    "Things in the kitchen",
    "Things in the sky",
    "Things that are black",
    "Things that are cold",
    "Things that are hot",
    "Things that are round",
    "Things that are square",
    "Things that are sticky",
    "Things that can get you fired",
    "Things that can kill you",
    "Things that grow",
    "Things that have buttons",
    "Things that have spots",
    "Things that have stripes",
    "Things that have wheels",
    "Things that jump/bounce",
    "Things that make you smile",
    "Things that use a remote",
    "Things to do at a party",
    "Things to do on a date",
    "Things with tails",
    "Things you buy for kids",
    "Things you do at work",
    "Things you do everyday",
    "Things you get in the mail",
    "Things you get tickets for",
    "Things you make",
    "Things you replace",
    "Things you save up to buy",
    "Things you see at the zoo",
    "Things you shouldn\u2019t touch",
    "Things you shout",
    "Things you sit/on",
    "Things you store items in",
    "Things you throw away",
    "Things you wear",
    "Things you\u2019re allergic to",
    "Titles people can have",
    "Tools",
    "Tourist attractions",
    "Toys",
    "Trees",
    "Types of drinks",
    "Types of weather",
    "Vacation spots",
    "Vegetables",
    "Video games",
    "Villains",
    "Ways to get from here to there",
    "Ways to kill time",
    "Websites",
    "Weekend Activities",
    "Wireless things",
    "Words associated with exercise",
    "Words associated with money",
    "Words associated with winter",
    "Words ending in \u201c-n\u201d",
    "Words with double letters",
    "World leaders/politicians"
];
